/**
* @providesModule skydreamer/redux/actions/types
*/

// Authentication types
export const SET_AUTH_STATE  = `SET_AUTH_STATE`;
export const SET_AUTH_TOKEN  = `SET_AUTH_TOKEN`;
export const SET_FIREBASE_ID  = `SET_FIREBASE_ID`;

// SwipeCard types
export const SET_SWIPECARD_FETCHING  = `SET_SWIPECARD_FETCHING`;
export const SET_SWIPECARD_FETCH_REQUIRED  = `SET_SWIPECARD_FETCH_REQUIRED`;
export const SET_SWIPECARD_EMPTY  = `SET_SWIPECARD_EMPTY`;
export const APPEND_SWIPECARDS  = `ADD_SWIPECARDS`;
export const POP_SWIPECARD  = `POP_SWIPECARD`;
export const RESET_SWIPECARDS = `RESET_SWIPECARDS`;

// Firebase sessions
export const SET_SESSION  = `SET_SESSION`;
export const SELECT_SESSION  = `SELECT_SESSION`;
export const APPEND_CHAT_MESSAGE  = `APPEND_CHAT_MESSAGE`;
export const PREPEND_CHAT_MESSAGES  = `PREPEND_CHAT_MESSAGES`;

// User
export const SET_USER  = `SET_USER`;
export const SET_USER_PHOTO  = `SET_USER_PHOTO`;
export const SET_USER_SETTINGS  = `SET_USER_SETTINGS`;
export const USER_SESSIONS_FETCHING  = `USER_SESSIONS_FETCHING`;
export const USER_SESSIONS_SUCCESS  = `USER_SESSIONS_SUCCESS`;
export const FETCH_USER_BUDDIES = `FETCH_USER_BUDDIES`;
export const SET_TRAVEL_ID = `SET_TRAVEL_ID`;

// Caching
export const ADD_PHOTO_LINK  = `ADD_PHOTO_LINK`;

// SESSION GRADIENT
export const SET_SESSION_GRADIENT_OFFLINE  = `SET_SESSION_GRADIENT_OFFLINE`;

// Facebook api actions
export const SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER = `SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER`;
export const SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_SUCCESS = `SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_SUCCESS`;
export const SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_FAIL = `SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_FAIL`;
export const SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_CANCELLED = `SHARE_FB_LINK_WITH_COMMENT_DEFINED_BY_THE_USER_CANCELLED`;
export const SHARE_FB_LINK_WITH_PREDEFINED_COMMENT = `SHARE_FB_LINK_WITH_PREDEFINED_COMMENT`;
export const SHARE_FB_LINK_WITH_PREDEFINED_COMMENT_SUCCESS = `SHARE_FB_LINK_WITH_PREDEFINED_COMMENT_SUCCESS`;
export const SHARE_FB_LINK_WITH_PREDEFINED_COMMENT_FAIL = `SHARE_FB_LINK_WITH_PREDEFINED_COMMENT_FAIL`;
export const SEND_FB_APP_INVITE = `SEND_FB_APP_INVITE`;
export const SEND_FB_APP_INVITE_SUCCESS = `SEND_FB_APP_INVITE_SUCCESS`;
export const SEND_FB_APP_INVITE_FAIL = `SEND_FB_APP_INVITE_FAIL`;
export const SEND_FB_APP_INVITE_CANCELLED = `SEND_FB_APP_INVITE_CANCELLED`;
